### ISSUE TITLE
Don't commit binary files to Git

### ISSUE THREAD

**Issue by probonopd** [darkoverlordofdata/ShmupWarz-AppImage#2]
Please don't commit binary files to Git, it's considered bad practice (don't take my word for it - google around, e.g., https://robinwinslow.uk/2013/06/11/dont-ever-commit-binary-files-to-git/).

Instead, it would be good practice to write a script that puts together the AppImage e.g, on Travis CI, and use GitHub Releases for storage of the resulting binary AppImage. The https://github.com/probonopd/AppImages repository has many examples on how to do this.

**Comment by darkoverlordofdata** [comment]
I agree - thanks for catching that. I just needed to fix the .gitignore, I generated the project using bzr, which I'm just learning to use.
